<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PRC-20170801ZCL" name="Test" tests="2" failures="2" timestamp="30 Oct 2018 03:16:34 GMT" time="0.018" errors="0">
  <testcase name="f" time="0.003" classname="com.mavenTest.NewTest">
    <failure type="java.lang.RuntimeException" message="测试异常01">
      <![CDATA[java.lang.RuntimeException: 测试异常01
	at com.mavenTest.NewTest.f(NewTest.java:11)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="fa" time="0.0" classname="com.mavenTest.NewTest">
    <failure type="java.lang.RuntimeException" message="测试异常01">
      <![CDATA[java.lang.RuntimeException: 测试异常01
	at com.mavenTest.NewTest.fa(NewTest.java:17)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- fa -->
</testsuite> <!-- Test -->
